# -*- coding: utf-8 -*-
"""Aula1_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQASCX-K5tt-bueJVLANNvDMzjm8F-DX
"""

from google.colab import drive
drive.mount('/content/drive')



import pandas as pd

df = pd.read_csv("datasets/Gapminder.csv", sep=";")

df.head()

df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"Expec de vida", "pop":"pop total", "gdpPercap":"PIB"})

df.shape
#total de linhas e colunas

df.columns

df.dtypes
#Object é equivalente a string

df.tail()
#retorna as ultimas linhas

df.describe()

df["Continente"].unique()

#filtrando
asia = df.loc[df["Continente"] == "Asia"]
asia.head()

asia["Continente"].unique()

#agrupameno = groupby

df.groupby("Continente")["Pais"].nunique()

# qual a espectativa de vida para cada ano
df.groupby("Ano")["Expec de vida"].mean()

asia["PIB"].mean()

asia["PIB"].sum()

